config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  resources :tasks do
    post :update_row_order, on: :collection
  end

end

app/models/task.rb
class Task < ActiveRecord::Base

  include RankedModel
  ranks :row_order

  validates :title, presence:true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.rank(:row_order).all
    @task = Task.new
  end

  def update_row_order
    @task = Task.find(params['task']['task_id'])
    @task.row_order_position = params['task']['position']
    @task.save

    render nothing: true
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    respond_to do |format|
        format.html { redirect_to tasks_url }
        format.js {}
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url }
        format.js {}
      else
        format.html {}
        format.js { render :error, locals: { error_message: "Pls, write something to filed" } }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url }
        format.js {}
      else
        format.html { render :edit }
        format.js { render :error, locals: { error_message: "Pls, write something to field" } }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.js {}
    end
    @task.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :done, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f| %>
  <%= f.text_field :title, required: true %>
  <%= submit_tag submit_text %>
<% end %>

app/views/tasks/_task.html.erb
<tr id="task_<%= task.id %>" class="item" >
  <td class="td_move"><%= image_tag('move.png') %></td>
  <td class="td_checkbox">
    <%= form_for task, remote: true do |f| %>
      <%= f.check_box(:done, checked: task.done, id: "task_checkbox_#{task.id}", class: 'task_checkbox') %>
    <% end %>
  </td>
  <td class="td_title"><span class="<% if task.done==true %>done<% else %>undone<% end %>"><%= link_to task.title, edit_task_path(task), remote: true %></span></td>
  <td class="td_edit"><%= link_to image_tag('edit.png'), edit_task_path(task), remote: true %></td>
  <td class="td_delete"><%= link_to image_tag('trash.png'), task, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
</tr>

app/views/tasks/create.js.erb
$("<%= j(render @task) %>").appendTo("#tasks").effect('highlight', {}, 1000);
$("#task_title").val("");

app/views/tasks/destroy.js.erb
$("#task_<%= @task.id %>").remove();

app/views/tasks/edit.html.erb
<%= render 'form' %>
<%= link_to 'Cancel', tasks_path %>

app/views/tasks/edit.js.erb
$("#task_<%= @task.id %> .td_title").replaceWith('<td class="td_title" colspan="2"> <%= j(render 'form', submit_text: "Save") %> </td>');
$("#task_<%= @task.id %> .td_edit").remove();

app/views/tasks/error.js.erb
$("#error_message").html("<%= error_message %>");

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<%= render 'form', submit_text: "Add"%>

<div id="error_message"></div>

</br>

<table id="tasks">
  <tbody>
    <%= render @tasks %>
  </tbody>
</table>

<br>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Done:</strong>
  <%= @task.done %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$('#task_<%= @task.id %>').replaceWith('<%= j(render @task) %>')
$('#task_<%= @task.id %>').effect('highlight', {}, 1000);